## Basic Configuration
baseurl = "https://blog.funspaces.org"
languageCode = "ko-kr"

title = "Kenny's Blog"
theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "kennygithub"
googleAnalytics = "UA-71902268-1"
# enableRobotsTXT = true

summarylength = 30

paginate = 10

## Site Settings
[params]
    author = "Kenny Kang"
    title = "Kenny"
    # description = "..."
    # authorimage = ""
    # dateformat = "2006-01-02T15:04:05-0700"

    # sidebar, copyright & license
    copyright = "Kenny"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    # Table of Contents
    toc = "tocbot"

[params.social]
    github = "herblover"
    gravatar = "herblover@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Tags"
    weight = 200
    identifier = "tags"
    url = "/tags/"
